spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookmanagement?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 15130140362
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080